CREATE DATABASE IF NOT EXISTS Project2;
USE Project2;
SET SQL_SAFE_UPDATES = 0;

CREATE TABLE IF NOT EXISTS Advertisements
(Advertisement_ID SMALLINT unsigned,
Adv_Title VARCHAR(30),
Adv_Deets VARCHAR(100),
Adv_DateTime DATETIME, 
Price FLOAT(5,2),
User_ID VARCHAR(15),
Moderator_ID VARCHAR(15),
Category_ID VARCHAR(15),
Status_ID VARCHAR(2),

CONSTRAINT PK_ADVERT_ID PRIMARY KEY (Advertisement_ID),
CONSTRAINT FK_USER_ID FOREIGN KEY (User_ID) REFERENCES Users (User_ID) ON DELETE CASCADE,
CONSTRAINT FK_MOD_ID FOREIGN KEY (Moderator_ID) REFERENCES Moderators (User_ID) ON DELETE SET NULL,
CONSTRAINT FK_CAT_ID FOREIGN KEY (Category_ID) REFERENCES Categories (Category_ID) ON DELETE RESTRICT,
CONSTRAINT FK_STAT_ID FOREIGN KEY (Status_ID) REFERENCES Statuses (Status_ID) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS Categories
(Category_ID VARCHAR (3),
Cat_Name VARCHAR(20),

CONSTRAINT PK_CAT_ID PRIMARY KEY (Category_ID)
);

CREATE TABLE IF NOT EXISTS Statuses
(Status_ID VARCHAR(2),
Status_Name VARCHAR(15),

CONSTRAINT PK_STAT_ID PRIMARY KEY (Status_ID)
);

CREATE TABLE IF NOT EXISTS Users
(User_ID VARCHAR (15),
UserFirstName VARCHAR(15),
UserLastName VARCHAR(15),

CONSTRAINT PK_USER_ID PRIMARY KEY (User_ID)
);

CREATE TABLE IF NOT EXISTS Moderators
(User_ID VARCHAR (15),

CONSTRAINT PK_MOD_ID PRIMARY KEY (User_ID),
CONSTRAINT FK_MOD_ID FOREIGN KEY (User_ID) REFERENCES Users (User_ID) ON DELETE RESTRICT
);


