CREATE DATABASE IF NOT EXISTS Project2;
USE Project2;
SET SQL_SAFE_UPDATES = 0;

CREATE TABLE IF NOT EXISTS ADVERTISEMENTS
(ADVERTISEMENT_ID VARCHAR(4),
ADV_TITLE VARCHAR(30),
ADV_DETAILS VARCHAR(100),
ADV_DATETIME datetime, 
PRICE float(2),
USER_ID VARCHAR(15),
MODERATOR_ID VARCHAR(15),
CATEGORY_ID VARCHAR(15),
STATUS_ID VARCHAR(2)
);

